/-
  scripts/ExportVectors.lean

  Writes the regression vectors of the paclet's emulation functions
  (TuringMachine/Kernel/Emulation.wl) from the Lean definitions: every
  encoder, evolution and decoder of the chain evaluated on the fixtures of
  Vectors/, printed as Wolfram Language expressions. The paclet test
  TuringMachine/Tests/Emulation.wlt compares the two.

      lake env lean scripts/ExportVectors.lean > ../TuringMachine/Tests/EmulationVectors.wl
-/

import Vectors.SmithVectors
import Vectors.TMToCTSVectors
import Smith.Infinite

open Smith BiTM TM TagSystem Tests

namespace Export

def list {α : Type} (f : α → String) (l : List α) : String :=
  "{" ++ ", ".intercalate (l.map f) ++ "}"

def nat (n : Nat) : String := toString n
def int (n : Int) : String := toString n
def bit (b : Bool) : String := if b then "1" else "0"
def str (s : String) : String := "\"" ++ s ++ "\""
def opt {α : Type} (f : α → String) : Option α → String
  | none => "Missing[]"
  | some a => f a

def dir : Dir → String
  | Dir.L => "-1"
  | Dir.R => "1"

def machine (tm : Machine) : String :=
  list (fun (qa : Nat × Nat) =>
    let r := tm.transition qa.1 qa.2
    "{" ++ nat qa.1 ++ ", " ++ nat qa.2 ++ "} -> {" ++ nat r.nextState ++ ", " ++ nat r.write ++
      ", " ++ dir r.dir ++ "}")
    ((List.range tm.numStates).flatMap fun q => [(q, 0), (q, 1)])

def cfg (c : BiTM.Config) : String :=
  "{" ++ nat c.state ++ ", " ++ list nat c.left ++ ", " ++ nat c.head ++ ", " ++ list nat c.right ++ "}"

def cts (C : CTS) (c : CTSConfig) : String :=
  "<|\"Appendants\" -> " ++ list (list bit) C.appendants ++ ", \"Data\" -> " ++ list bit c.data ++
    ", \"Phase\" -> " ++ nat c.phase ++ "|>"

def ctsCfg (c : CTSConfig) : String :=
  "{" ++ list bit c.data ++ ", " ++ nat c.phase ++ "}"

def s5 (s : System5Config) : String :=
  "<|\"Bag\" -> " ++ list int s.bag ++ ", \"Rules\" -> " ++ list (list int) s.rules ++ "|>"

def st4 : System4State → String
  | System4State.A => str "A"
  | System4State.B => str "B"
  | System4State.C => str "C"

def elem : System4Elem → String
  | System4Elem.star => str "*"
  | System4Elem.set S => list int S

def s4 (c : System4Config) : String :=
  "<|\"Elements\" -> " ++ list elem c.elems ++ ", \"Active\" -> " ++ nat c.active ++
    ", \"State\" -> " ++ st4 c.state ++ "|>"

def lst : LState → String
  | LState.A => str "A"
  | LState.B => str "B"
  | LState.C => str "C"

def s3 (c : LConfig) : String :=
  "<|\"Left\" -> " ++ list (fun (x : Fin 3) => nat x.val) c.left ++ ", \"Head\" -> " ++ nat c.head.val ++
    ", \"Right\" -> " ++ list (fun (x : Fin 3) => nat x.val) c.right ++ ", \"State\" -> " ++ lst c.state ++ "|>"

def s3At (c : LConfig) (n : Nat) : String := opt s3 (lnSteps sys3 c n)

def entry (name val : String) : IO Unit := IO.println (name ++ " = " ++ val ++ ";")

end Export

open Export

def cfgH : BiTM.Config := ⟨1, [], 0, []⟩
def cfgEx : BiTM.Config := ⟨1, [], 0, [1, 1]⟩
def s3D9v : LConfig := (initAC 3 3 [0, 2] [System4Elem.star, System4Elem.set []]).toL
def s3D10v : LConfig := (initAC 3 3 [0, 2, 4, 6] [System4Elem.star, System4Elem.set []]).toL
def s4Small : System4Config := system5ToSystem4 s5D4 3

def main : IO Unit := do
  IO.println "(* Generated by Proofs/scripts/ExportVectors.lean; do not edit. *)"
  IO.println "(* :!CodeAnalysis::BeginBlock:: *)"
  -- machines and the Cocke-Minsky tag system
  entry "tmH" (machine tmH)
  entry "tmEx" (machine tmEx)
  for (nm, tm, c) in [("H", tmH, cfgH), ("Ex", tmEx, cfgEx)] do
    let S := tm.numStates
    entry s!"cfg{nm}" (cfg c)
    entry s!"productions{nm}" (list (fun i => list (fun (j : Fin (1 + 84 * S)) => nat j.val)
      ((tagK tm S).productions i)) (List.finRange (1 + 84 * S)))
    entry s!"word{nm}" (list (fun (j : Fin (1 + 84 * S)) => nat j.val) ((word c).map (enc S)))
    entry s!"tagRun{nm}" (list (fun t => opt (list (fun (j : Fin (1 + 84 * S)) => nat j.val))
      (nStepsP (prod tm) (word c) t |>.map (·.map (enc S)))) (List.range 40))
    entry s!"tagTimes{nm}" (list (fun n => nat (tagTime tm c n)) (List.range 5))
    entry s!"rawRun{nm}" (list (fun n => cfg (rawRun tm c n)) (List.range 5))
    entry s!"cts{nm}" (cts (ctsOf tm) (ctsOfCfg S c))
    entry s!"ctsRun{nm}" (list (fun t => opt ctsCfg ((ctsOf tm).nSteps (ctsOfCfg S c) t))
      [0, 1, 2, 3, 50, 169, 338, 1000, 2028])
    entry s!"decodeCTS{nm}" (list (fun n => opt cfg (decodeCTS S (ctsOfCfg S (rawRun tm c n))))
      (List.range 3))
    entry s!"decodeWord{nm}" (list (fun n => opt cfg (decodeWord (word (rawRun tm c n))))
      (List.range 3))
  -- cyclic tag to System 5
  entry "ctsD1" (cts ctsD1 cfgD1)
  entry "ctsD2" (cts ctsD2 cfgD2)
  entry "ctsD1p1" (cts ctsD1 { data := [false, true], phase := 1 })
  entry "s5D1n1" (s5 (ctsToSystem5 ctsD1 cfgD1 1))
  entry "s5D1n2" (s5 (ctsToSystem5 ctsD1 cfgD1 2))
  entry "s5D1p1" (s5 (ctsToSystem5 ctsD1 { data := [false, true], phase := 1 } 1))
  entry "s5D2n3" (s5 (ctsToSystem5 ctsD2 cfgD2 3))
  entry "s5Run" (list (fun t => opt s5 (System5.nSteps (ctsToSystem5 ctsD1 cfgD1 1) t)) (List.range 12))
  entry "s5D2n3Length" (nat (((List.range 20000).find? fun t =>
    (System5.nSteps (ctsToSystem5 ctsD2 cfgD2 3) (t + 1)).isNone).getD 0))
  entry "decodeBags" (list (fun b => opt (list bit) (decodeBag b))
    [[1, 2, 3, 4, 5, 7, 8, 10], [2, 1], [1, 3], [1, 4], [0, 1], [1, 2, 3], [], [5, 6, 3, 4]])
  -- System 5 to System 4
  entry "s5D4" (s5 s5D4)
  entry "s4D4" (s4 s4D4)
  entry "s4Small" (s4 s4Small)
  entry "s4SmallRun" (list (fun t => opt s4 (System4.nSteps s4Small t)) (List.range 60))
  entry "s4D4Length" (nat (((List.range 20000).find? fun t => (System4.nSteps s4D4 (t + 1)).isNone).getD 0))
  entry "decodeS4" (list (fun t => opt (fun c => opt (list int) (decodeS4 c 8)) (System4.nSteps s4Small t))
    (List.range 60))
  entry "icD4" (list nat [icB s5D4, icT5 s5D4, icM s5D4, icH s5D4, icF s5D4, icBand s5D4])
  -- System 4 to System 3 to wolfram23
  entry "s3D9" (s3 s3D9v)
  entry "s3D10" (s3 s3D10v)
  entry "s3Small" (s3 (initAC 4 5 (encodeBag s5D4.bag) [System4Elem.star, System4Elem.set [0, 3]]).toL)
  entry "s3D9Run" (list (fun t => s3At s3D9v t) (List.range 120))
  entry "w23D9Run" (list (fun t => opt (fun c => cfg (toBi (phi2 (phi3 c)))) (lnSteps sys3 s3D9v t)) (List.range 120))
  entry "w23D9" (cfg (toBi (phi2 (phi3 s3D9v))))
  entry "w23D9Steps" (list (fun t => opt cfg (BiTM.nSteps wolfram23 (toBi (phi2 (phi3 s3D9v))) t)) (List.range 200))
  entry "decodeW23D9" (list (fun t => opt (fun c => opt (list int) (decodeBlocks 8 4 (c.head :: c.right.takeWhile (fun x => x != 0))))
    (BiTM.nSteps wolfram23 (toBi (phi2 (phi3 s3D9v))) t)) (List.range 200))
  entry "decodeW23D10" (list (fun t => opt (fun c => opt (list int) (decodeBlocks 8 8 (c.head :: c.right.takeWhile (fun x => x != 0))))
    (BiTM.nSteps wolfram23 (toBi (phi2 (phi3 s3D10v))) t)) (List.range 200))
  IO.println "(* :!CodeAnalysis::EndBlock:: *)"

#eval main
