PacletObject[
  <|
    "Name" -> "WolframInstitute/TuringMachine",
    "Description" -> "Tools for exploring and analyzing Turing machines",
    "Creator" -> "Nik Murzin and Willem Nielsen",
    "License" -> "MIT",
    "PublisherID" -> "WolframInstitute",
    "Version" -> "1.1.3",
    "WolframVersion" -> "14.3+",
    "PrimaryContext" -> "WolframInstitute`TuringMachine`",
    "Extensions" -> {
      {
        "Kernel",
        "Root" -> "Kernel",
        "Context" -> "WolframInstitute`TuringMachine`",
        "Symbols" -> {
          "WolframInstitute`TuringMachine`MultiwayNonHaltedStatesLeft",
          "WolframInstitute`TuringMachine`MultiwayTuringMachineFunction",
          "WolframInstitute`TuringMachine`MultiwayTuringMachineRules",
          "WolframInstitute`TuringMachine`MultiwayTuringMachine",
          "WolframInstitute`TuringMachine`NonTerminatingTuringMachineQ",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineFind",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineFunction",
          "WolframInstitute`TuringMachine`OneSidedTuringMachinePlot",
          "WolframInstitute`TuringMachine`TuringMachineOutput",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithSteps",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithStepsFloat",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithStepsWidths",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithStepsWidthsFloat",
          "WolframInstitute`TuringMachine`TuringMachineRuleCases",
          "WolframInstitute`TuringMachine`TuringMachineRuleCount",
          "WolframInstitute`TuringMachine`TuringMachineSteps",
          "WolframInstitute`TuringMachine`TuringMachineStepsWidths",
          "WolframInstitute`TuringMachine`TuringMachineWidths",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineEvolution",
          "WolframInstitute`TuringMachine`$PvsNPStyles",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineFunctionPlot",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineRuntimePlot",
          "WolframInstitute`TuringMachine`MultiwayTuringMachinePlot",
          "WolframInstitute`TuringMachine`TuringMachineWorstCasePlot",
          "WolframInstitute`TuringMachine`InductiveProofs`DecodeTuringMachineRules",
          "WolframInstitute`TuringMachine`InductiveProofs`RunMachine",
          "WolframInstitute`TuringMachine`InductiveProofs`CompressToRunLength",
          "WolframInstitute`TuringMachine`InductiveProofs`FindInductiveProof",
          "WolframInstitute`TuringMachine`InductiveProofs`cachedProofFor",
          "WolframInstitute`TuringMachine`InductiveProofs`mergedProofFor",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderConfiguration",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderEquation",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderAxiomGrid",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderUniversalGoal",
          "WolframInstitute`TuringMachine`InductiveProofs`ShowTapeConfiguration",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwaySystemFor",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwaySubProofCones",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwayDistance",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayEquationalGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayGeodesicGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayTokenEventGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`proofGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`IslandsPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`StatementPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`TokenEventPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayBothPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`SettingsPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`RuleSpacePanel",
          "WolframInstitute`TuringMachine`InductiveProofs`inductionProofGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwayCloudOverlap",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayRuleGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayInductiveProofPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`$InductiveProofColors"
        }
      },
      {
        "LibraryLink"
      },
      {
        "Documentation",
        "Root" -> "Documentation",
        "Language" -> "English"
      }
    }
  |>
]