PacletObject[
  <|
    "Name" -> "WolframInstitute/TuringMachine",
    "Description" -> "Tools for exploring and analyzing Turing machines",
    "Creator" -> "Wolfram Institute",
    "License" -> "MIT",
    "PublisherID" -> "WolframInstitute",
    "Version" -> "1.4.0",
    "WolframVersion" -> "14.3+",
    "PrimaryContext" -> "WolframInstitute`TuringMachine`",
    "Extensions" -> {
      {
        "Kernel",
        "Root" -> "Kernel",
        "Context" -> {"WolframInstitute`TuringMachine`", {"WolframInstitute`TuringMachine`InductiveProofs`", "InductiveProofs.wl"}},
        "Symbols" -> {
          "WolframInstitute`TuringMachine`MultiwayNonHaltedStatesLeft",
          "WolframInstitute`TuringMachine`MultiwayTuringMachineFunction",
          "WolframInstitute`TuringMachine`MultiwayTuringMachineRules",
          "WolframInstitute`TuringMachine`MultiwayTuringMachine",
          "WolframInstitute`TuringMachine`NonTerminatingTuringMachineQ",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineFind",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineFunction",
          "WolframInstitute`TuringMachine`OneSidedTuringMachinePlot",
          "WolframInstitute`TuringMachine`TuringMachineOutput",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithSteps",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithStepsFloat",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithStepsWidths",
          "WolframInstitute`TuringMachine`TuringMachineOutputWithStepsWidthsFloat",
          "WolframInstitute`TuringMachine`TuringMachineRuleCases",
          "WolframInstitute`TuringMachine`TuringMachineRuleCount",
          "WolframInstitute`TuringMachine`TuringMachineSteps",
          "WolframInstitute`TuringMachine`TuringMachineStepsWidths",
          "WolframInstitute`TuringMachine`TuringMachineWidths",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineEvolution",
          "WolframInstitute`TuringMachine`$PvsNPStyles",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineFunctionPlot",
          "WolframInstitute`TuringMachine`OneSidedTuringMachineRuntimePlot",
          "WolframInstitute`TuringMachine`MultiwayTuringMachinePlot",
          "WolframInstitute`TuringMachine`TuringMachineWorstCasePlot",
          "WolframInstitute`TuringMachine`TagSystem",
          "WolframInstitute`TuringMachine`CyclicTagSystem",
          "WolframInstitute`TuringMachine`System5",
          "WolframInstitute`TuringMachine`System4",
          "WolframInstitute`TuringMachine`System3",
          "WolframInstitute`TuringMachine`TuringMachineToTagSystem",
          "WolframInstitute`TuringMachine`TagSystemToCyclicTagSystem",
          "WolframInstitute`TuringMachine`CyclicTagSystemToSystem5",
          "WolframInstitute`TuringMachine`System5ToSystem4",
          "WolframInstitute`TuringMachine`System4ToSystem3",
          "WolframInstitute`TuringMachine`System3ToWolfram23",
          "WolframInstitute`TuringMachine`TagSystemToTuringMachine",
          "WolframInstitute`TuringMachine`CyclicTagSystemToTagSystem",
          "WolframInstitute`TuringMachine`System5ToCyclicTagSystem",
          "WolframInstitute`TuringMachine`System4ToSystem5",
          "WolframInstitute`TuringMachine`Wolfram23ToSystem5",
          "WolframInstitute`TuringMachine`TagSystemEvolution",
          "WolframInstitute`TuringMachine`CyclicTagSystemEvolution",
          "WolframInstitute`TuringMachine`System5Evolution",
          "WolframInstitute`TuringMachine`System4Evolution",
          "WolframInstitute`TuringMachine`System3Evolution",
          "WolframInstitute`TuringMachine`Wolfram23Evolution",
          "WolframInstitute`TuringMachine`EmulationParameters",
          "WolframInstitute`TuringMachine`EmulationSizes",
          "WolframInstitute`TuringMachine`TagSystemEvolutionPlot",
          "WolframInstitute`TuringMachine`CyclicTagSystemEvolutionPlot",
          "WolframInstitute`TuringMachine`System5EvolutionPlot",
          "WolframInstitute`TuringMachine`System4EvolutionPlot",
          "WolframInstitute`TuringMachine`System3EvolutionPlot",
          "WolframInstitute`TuringMachine`Wolfram23EvolutionPlot",
          "WolframInstitute`TuringMachine`TuringMachineEvolutionPlot",
          "WolframInstitute`TuringMachine`ParityBlock",
          "WolframInstitute`TuringMachine`InductiveProofs`DecodeTuringMachineRules",
          "WolframInstitute`TuringMachine`InductiveProofs`RunMachine",
          "WolframInstitute`TuringMachine`InductiveProofs`CompressToRunLength",
          "WolframInstitute`TuringMachine`InductiveProofs`FindInductiveProof",
          "WolframInstitute`TuringMachine`InductiveProofs`cachedProofFor",
          "WolframInstitute`TuringMachine`InductiveProofs`mergedProofFor",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderConfiguration",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderEquation",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderAxiomGrid",
          "WolframInstitute`TuringMachine`InductiveProofs`RenderUniversalGoal",
          "WolframInstitute`TuringMachine`InductiveProofs`ShowTapeConfiguration",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwaySystemFor",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwaySubProofCones",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwayDistance",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayEquationalGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayGeodesicGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayTokenEventGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`proofGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`IslandsPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`StatementPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`TokenEventPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayBothPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`SettingsPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`RuleSpacePanel",
          "WolframInstitute`TuringMachine`InductiveProofs`inductionProofGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`multiwayCloudOverlap",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayRuleGraph",
          "WolframInstitute`TuringMachine`InductiveProofs`MultiwayInductiveProofPanel",
          "WolframInstitute`TuringMachine`InductiveProofs`$InductiveProofColors",
          "WolframInstitute`TuringMachine`InductiveProofs`transitionAxiomsFor",
          "WolframInstitute`TuringMachine`InductiveProofs`boundaryAxiomsFor",
          "WolframInstitute`TuringMachine`InductiveProofs`unboundAxiom",
          "WolframInstitute`TuringMachine`InductiveProofs`onesRunDefinitions",
          "WolframInstitute`TuringMachine`InductiveProofs`zerosRunDefinitions",
          "WolframInstitute`TuringMachine`InductiveProofs`goalFor",
          "WolframInstitute`TuringMachine`InductiveProofs`forAllBody"
        }
      },
      {
        "Asset",
        "Root" -> ".",
        "Assets" -> {
          {"Binaries", "Binaries"}
        }
      },
      {
        "Documentation",
        "Root" -> "Documentation",
        "Language" -> "English"
      }
    }
  |>
]